/*
NOTE ON THIS SECTION

    THESE PROBLEMS ARE SIGNIFICANTLY HARDER THAN THE EARLIER PROBLEMS.  DO NOT FEEL BAD IF THEY GIVE YOU TROUBLE.  THIS SECTION IS FOR PEOPLE WHO ENJOY PAIN AND MISERY.  YOU DO NOT NEED TO ATTEMPT ANY OF THESE PROBLEMS IF YOU DO NOT WANT TO! 
本節の注釈
これらの問題は、これまでの問題よりかなり難しくなっています。
このセクションは、苦痛や不幸を楽しむ人たちのためのものです。
もし、これらの問題に挑戦したくなければ、挑戦する必要はありません。
    */
